import {
  Home,
  PatientSearch,
  Triage,
  OPD,
  IPD,
  Pharmacy,
  Radiology,
  Laboratory,
  Billing,
  UserProfile,
  ProviderScheduling,
  PatientRegistration,
  OnlinePatients,
  SystemAdmin,
  PatientEdit,
} from "../pages";
import BillingTabHomeComponent from "../pages/Billing/BillingTabHomeComponent";
import ListtoOrder from "../pages/Billing/ListtoOrder";
import OpdQue from "../pages/Billing/OpdQue";
import SearchWalkingPatient from "../pages/Billing/SearchWalkingPatient";
import ManageDrugIssue from "../pages/Pharmacy/ManageDrugsIssue";
import IndentDrugs from "../pages/Pharmacy/IndentDrugs";
import IssueDrugToAccountReturn from "../pages/Pharmacy/IssueDrugToAccountReturn";
import IssueDrugToPatient from "../pages/Pharmacy/IssueDrugToPatient";
import PatientQueue from "../pages/Pharmacy/PatientQueue";
import ViewStockBalance from "../pages/Pharmacy/ViewStockBalance";
import ViewStockBalanceExpiry from "../pages/Pharmacy/ViewStockBalanceExpiry";
import MainStoreTabs from "../pages/MainStore/ViewStocKBalance";
import VoidBill from "../pages/Pharmacy/VoidBill";
import ManageDrugs from "../pages/SystemAdministration/Inventory/ManageDrugs";
import ManageItem from "../pages/SystemAdministration/Inventory/ManageItem";
import ManageStore from "../pages/SystemAdministration/Inventory/ManageStore";
import ManageCategory from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageCategory"
import ManageSubCategory from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageSubCategory"
import ManageSpecification from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageSpecification"
import ManageItemTab from "../pages/SystemAdministration/Inventory/ItemSubTab/manageItem"
import ManageUnit from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageUnit"
import ManageUnitTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageUnitTab"
import ManageCategoryTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageCategoryTab"
import ManageFormulationTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageFormulationTab"
import ManageDrugsTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageDrugsTab"
import AddStore from "../pages/SystemAdministration/Inventory/ManageStore/AddStore"
import UpdateStore from "../pages/SystemAdministration/Inventory/ManageStore/EditStore"
import AddItem from "../pages/SystemAdministration/Inventory/ManageItem/AddItem"
import UpdateItem from "../pages/SystemAdministration/Inventory/ManageItem/UpdateItem"
import AddCategory from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageCategory/AddCategory"
import UpdateCategory from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageCategory/UpdateCategory"
import AddUnit from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageUnit/AddUnit"
import UpdateUnit from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageUnit/UpdateUnit"
import AddSubCategory from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageSubCategory/AddSubCategory"
import UpdateSubCategory from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageSubCategory/UpdateSubCategory"
import AddSpecification from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageSpecification/AddSpecification"
import UpdateSpecification from "../pages/SystemAdministration/Inventory/ItemSubTab/ManageSpecification/UpdateSpecification"
import AddUnitTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageUnitTab/AddUnitTab"
import UpdateUnitTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageUnitTab/UpdateUnitTab"
import AddCategoryTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageCategoryTab/AddCategoryTab"
import UpdateCategoryTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageCategoryTab/UpdateCategoryTab"
import AddFormulationTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageFormulationTab/AddFormulation"
import UpdateFormulationTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageFormulationTab/UpdateFormulation"
import AddDrugTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageDrugsTab/AddDrug"
import UpdateDrugTab from "../pages/SystemAdministration/Inventory/DrugSubTab/ManageDrugsTab/UpdateDrug"
import MSViewStockBalance from "../pages/MainStore/ViewStocKBalance"
import MSViewStockBalanceExpiry from "../pages/MainStore/ViewStockBalanceExpiry"
import MSRecieptsToGeneralStore from "../pages/MainStore/ReceiptsToGeneralStore"
import MSTransferFromGeneralStore from "../pages/MainStore/TransferFromGeneralStore"
import AddReceipt from "../pages/MainStore/AddReceipt"
import ReceiptDetail from "../pages/MainStore/ReceiptDetail"
import FinishSlip from "../pages/MainStore/FinishSlip"
import ViewStockBalanceDetail from "../pages/MainStore/ViewStockBalanceDetail"
import ToStoreDetail from "../pages/MainStore/ToStoreDetail"
import DrugIndentDetail from "../pages/MainStore/DrugIndentDetail"
import IndentProcess from "../pages/MainStore/ProcessIndent"
import BillingAmbulance from "../pages/Billing/BillingAmbulance";
import BillingTenderList from "../pages/Billing/BillingTender/BillingTenderCompnayList";
// import AddNewBillingAmbulanceDriver from "../pages/Billing/BillingAmbulance/AddNewDriver";

/**
 * list of available routes for the entire application.
 */
export const appRoutes = [
  {
    path: "/home",
    title: "Home",
    roles: ["*"],
    visibleOnSidebar: true,
    icon: "fa fa-clinic-medical",
    component: Home,
    layout: "/app",
  },
  {
    path: "/patient-search",
    title: "Patient Search",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-user-plus",
    component: PatientSearch,
    layout: "/app",
  },
  {
    path: "/online-appointments",
    title: "Online Appointments",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-calendar-check",
    component: OnlinePatients,
    layout: "/app",
  },
  {
    path: "/patient-registration",
    title: "Patient Registration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user-plus",
    component: PatientRegistration,
    layout: "/app",
  },
  {
    path: "/edit-patient/:id",
    title: "Edit Patient",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user-plus",
    component: PatientEdit,
    layout: "/app",
  },
  {
    path: "/triage",
    title: "Triage",
    roles: [
      "System Developer",
      "Organizational: Doctor",
      "Application: Enter ADT events",
      "Application: Record allergies",
      "Application: Requests appointments",
      "Application: Sees appointment schedule",
      "Application: Uses patient summary",
      "Application: Writes clinical notes",
    ],
    visibleOnSidebar: true,
    icon: "fas fa-heartbeat",
    component: Triage,
    layout: "/app",
  },
  {
    path: "/opd",
    title: "OPD",
    roles: [
      "System Developer",
      "Organizational: Doctor",
      "Application: Enter ADT events",
      "Application: Record allergies",
      "Application: Requests appointments",
      "Application: Sees appointment schedule",
      "Application: Uses patient summary",
      "Application: Writes clinical notes",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-user-md",
    component: OPD,
    layout: "/app",
  },
  {
    path: "/ipd",
    title: "IPD",
    roles: [
      "System Developer",
      "Organizational: Nurse",
      "Application: Enter ADT events",
      "Application: Enter vitals",
      "Application: Record allergies",
      "Application: Requests appointments",
      "Application: Sees appointment schedule",
      "Application: Uses patient summary",
      "Application: Uses capture vitals app",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-procedures",
    component: IPD,
    layout: "/app",
  },
  {
    path: "/pharmacy/home",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: true,
    icon: "fa fa-prescription-bottle-alt",
    component: ManageDrugIssue,
    layout: "/app",
  },
  {
    path: "/pharmacy/indent_drugs",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: IndentDrugs,
    layout: "/app",
  },
   {
    path: "/pharmacy/issue_drug_to_patient",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: IssueDrugToPatient,
    layout: "/app",
  },
   {
    path: "/pharmacy/issue_drug_to_account_return",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: IssueDrugToAccountReturn,
    layout: "/app",
  },
   {
    path: "/pharmacy/patient_queue",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: PatientQueue,
    layout: "/app",
  },
   {
    path: "/pharmacy/view_stock_balance",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: ViewStockBalance,
    layout: "/app",
  },
   {
    path: "/pharmacy/view_stock_balance_expiry",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: ViewStockBalanceExpiry,
    layout: "/app",
  },
   {
    path: "/pharmacy/void_bill",
    title: "Pharmacy",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: VoidBill,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_store",
    title: "System Administration",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: ManageStore,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_item",
    title: "System Administration",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: ManageItem,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_drug",
    title: "System Administration",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: false,
    icon: "fa fa-prescription-bottle-alt",
    component: ManageDrugs,
    layout: "/app",
  },
  {
    path: "/billing/home",
    title: "Billing",
    roles: [
      "System Developer",
      "Application: Billing Administrator",
      "Application: Billing Clerk",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-receipt",
    component: BillingTabHomeComponent,
    layout: "/app",
  },
  {
    path: "/billing/outpatientbillingqueue",
    title: "",
    roles: [
      "System Developer",
      "Application: Billing Administrator",
      "Application: Billing Clerk",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-receipt",
    component: OpdQue,
    layout: "/app",
  },


  // billing mobile routes by prem
  {
    path: "/billing/billingambulancequeue",
    title: "",
    roles: [
      "System Developer",
      "Application: Billing Administrator",
      "Application: Billing Clerk",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user-plus",
    component: BillingAmbulance,
    layout: "/app",
  },
  {
    path: "/billing/billingTenderqueue",
    title: "",
    roles: [
      "System Developer",
      "Application: Billing Administrator",
      "Application: Billing Clerk",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user-plus",
    component: BillingTenderList,
    layout: "/app",
  },

  // add new paitent

  // {
  //   path: "/billing/addbillingambulancedriver",
  //   title: "",
  //   roles: [
  //     "System Developer",
  //     "Application: Billing Administrator",
  //     "Application: Billing Clerk",
  //   ],
  //   visibleOnSidebar: false,
  //   icon: "fa fa-user-plus",
  //   component: AddNewBillingAmbulanceDriver ,
  //   layout: "/app",
  // },
  {
    path: "/billing/searchwalkingqueue",
    title: "",
    roles: [
      "System Developer",
      "Application: Billing Administrator",
      "Application: Billing Clerk",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-receipt",
    component: SearchWalkingPatient,
    layout: "/app",
  },
  {
    path: "/billing/listtoorder/:id/:param2",
    title: "",
    roles: [
      "System Developer",
      "Application: Billing Administrator",
      "Application: Billing Clerk",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-receipt",
    component: ListtoOrder,
    layout: "/app",
  },
  {
    path: "/laboratory",
    title: "Laboratory",
    roles: [
      "System Developer",
      "Organizational: Laboratory Administrator",
      "Application: Laboratory Technician",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-vials",
    component: Laboratory,
    layout: "/app",
  },
  {
    path: "/radiology",
    title: "Radiology",
    roles: [
      "System Developer",
      "Organizational: Radiology Administrator",
      "Application: Radiology Technician",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-x-ray",
    component: Radiology,
    layout: "/app",
  },
  {
    path: "/user-profile",
    title: "User Profile",
    roles: ["*"],
    visibleOnSidebar: false,
    icon: "",
    component: UserProfile,
    layout: "/app",
  },
  {
    path: "/schedule-provider",
    title: "Provider Schedule",
    roles: ["*"],
    visibleOnSidebar: true,
    icon: "fa fa-calendar-alt",
    component: ProviderScheduling,
    layout: "/app",
  },
  {
    path: "/system-administration",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: true,
    icon: "fa fa-user",
    component: SystemAdmin,
    layout: "/app",
  },
  {
    path: "/main_store/ms_view_stock_balance",
    title: "Main Store",
    roles: ["System Developer", "Organizational: Pharmacy"],
    visibleOnSidebar: true,
    icon: "fas fa-warehouse",
    component: MSViewStockBalance,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageCategory,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_sub_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageSubCategory,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_specification",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageSpecification,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_unit",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageUnit,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_item",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageItemTab,
    layout: "/app",
  },
  {
    path: "/system-administration/drug_manage_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageCategoryTab,
    layout: "/app",
  },
  {
    path: "/system-administration/drug_manage_unit",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageUnitTab,
    layout: "/app",
  },
  {
    path: "/system-administration/drug_manage_formulation",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageFormulationTab,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_drug",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: ManageDrugsTab,
    layout: "/app",
  },
  {
    path: "/system-administration/add_store",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddStore,
    layout: "/app",
  },
  {
    path: "/system-administration/update_store",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateStore,
    layout: "/app",
  },
  {
    path: "/system-administration/add_item",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddItem,
    layout: "/app",
  },
  {
    path: "/system-administration/update_item",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateItem,
    layout: "/app",
  },
  {
    path: "/system-administration/add_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddCategory,
    layout: "/app",
  },
  {
    path: "/system-administration/update_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateCategory,
    layout: "/app",
  },
  {
    path: "/system-administration/add_unit",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddUnit,
    layout: "/app",
  },
  {
    path: "/system-administration/update_unit",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateUnit,
    layout: "/app",
  },
  {
    path: "/system-administration/add_sub_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddSubCategory,
    layout: "/app",
  },
  {
    path: "/system-administration/update_sub_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateSubCategory,
    layout: "/app",
  },
  {
    path: "/system-administration/add_specification",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddSpecification,
    layout: "/app",
  },
  {
    path: "/system-administration/update_specification",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateSpecification,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_add_unit",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddUnitTab,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_update_unit",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateUnitTab,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_drug_add_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddCategoryTab,
    layout: "/app",
  }, 
  {
    path: "/system-administration/manage_drug_update_category",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateCategoryTab,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_drug_add_formulation",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddFormulationTab,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_drug_Update_formulation",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateFormulationTab,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_drug_add_drug",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: AddDrugTab,
    layout: "/app",
  },
  {
    path: "/system-administration/manage_drug_update_drug",
    title: "System Administration",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "fa fa-user",
    component: UpdateDrugTab,
    layout: "/app",
  },
  // {
  //   path: "/main_store/ms_view_stock_balance",
  //   title: "View Stock Balance",
  //   roles: [
  //     "System Developer",
  //     "Organizational: Registration clerk",
  //     "Application: Registers Patients",
  //     "Application: Schedules appointments",
  //     "Application: Sees appointment schedule",
  //   ],
  //   visibleOnSidebar: false,
  //   icon: "",
  //   component: MSViewStockBalance,
  //   layout: "/app",
  // },
  {
    path: "/main_store/view_stock_balance_expiry",
    title: "View Stock Balance Expiry",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: MSViewStockBalanceExpiry,
    layout: "/app",
  },
  {
    path: "/main_store/receipts_to_general_store",
    title: "Receipt to General Store",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: MSRecieptsToGeneralStore,
    layout: "/app",
  },
  {
    path: "/main_store/transfer_from_general_store",
    title: "Transfer From General Store",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: MSTransferFromGeneralStore,
    layout: "/app",
  },
  {
    path: "/main_store/add_receipt",
    title: "Add Receipt",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: AddReceipt,
    layout: "/app",
  },
  {
    path: "/main_store/receipt_detail",
    title: "Receipt Detail",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: ReceiptDetail,
    layout: "/app",
  },
  {
    path: "/main_store/finish_slip",
    title: "Finish Slip",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: FinishSlip,
    layout: "/app",
  },
  {
    path: "/main_store/view_stock_balance_detail",
    title: "View Stcok Balance Detail",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: ViewStockBalanceDetail,
    layout: "/app",
  },
  {
    path: "/main_store/to_store_detail",
    title: "To Store Detail",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: ToStoreDetail,
    layout: "/app",
  },
  {
    path: "/main_store/drug_indent_detail",
    title: "Drug Indent Detail",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: DrugIndentDetail,
    layout: "/app",
  },
  {
    path: "/main_store/indent_process",
    title: "Indent Process",
    roles: [
      "System Developer",
      "Organizational: Registration clerk",
      "Application: Registers Patients",
      "Application: Schedules appointments",
      "Application: Sees appointment schedule",
    ],
    visibleOnSidebar: false,
    icon: "",
    component: IndentProcess,
    layout: "/app",
  },
];


