export const FETCH_AVATAR = "FETCH_AVATAR";
export const REMVOE_AVATAR = "REMOVE_AVATAR";
export const FETCH_PROVIDERS = "FETCH_PROVIDERS";

//TO DELETE
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";

export const LOADING_LOCATIONS = "LOADING_LOCATIONS"
export const LOCATIONS_LOADED = "LOCATIONS_LOADED"

export const LOADING_VISITS = "LOADING_VISITS"
export const VISITS_LOADED = "VISITS_LOADED"

export const LOADING_PATIENT = "LOADING_PATIENT"
export const PATIENT_LOADED = "PATIENT_LOADED"

export const LOADING_CONCEPTS = "LOADING_CONCEPTS"
export const CONCEPTS_LOADED = "CONCEPTS_LOADED"

export const ENCOUNTER_TYPES_LOADED = "ENCOUNTER_TYPES_LOADED"
export const ENCOUNTER_TYPES_LOADING = "ENCOUNTER_TYPES_LOADING"

export const SAVING_PATIENT_HISTORY = "SAVING_PATIENT_HISTORY"
export const PATIENT_HISOTRY_SAVED = "PATIENT_HISOTRY_SAVED"

export const FETCH_SERVICES = "FETCH_SERVICES";
export const FETCH_APPOINTMENT_BLOCK_WITH_TIME_SLOTS =
  "FETCH_APPOINTMENT_BLOCK_WITH_TIME_SLOTS";
export const ADD_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "ADD_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
export const UPDATE_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "UPDATE_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
export const DELETE_APPOINTMENT_BLOCK_WITH_TIME_SLOT =
  "DELETE_APPOINTMENT_BLOCK_WITH_TIME_SLOT";
//
export const SET_STORE_DETAILS = "SET_STORE_DETAILS"
export const ADD_STORE = "ADD_STORE"
export const UPDATE_STORE = "UPDATE_STORE"
export const DELETE_STORE = "DELETE_STORE"

export const SET_ITEM_DETAILS = "SET_ITEM_DETAILS"
export const ADD_ITEM = "ADD_ITEM"
export const UPDATE_ITEM = "UPDATE_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"

export const SET_CATEGORY_DETAILS = "SET_CATEGORY_DETAILS"
export const ADD_CATETORY = "ADD_CATETORY"
export const UPDATE_CATEGORY= "UPDATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"

export const SET_UNIT_DETAILS = "SET_UNIT_DETAILS"
export const ADD_UNIT = "ADD_UNIT"
export const UPDATE_UNIT= "UPDATE_UNIT"
export const DELETE_UNIT = "DELETE_UNIT"

export const SET_SUB_CATEGORY_DETAILS = "SET_SUB_CATEGORY_DETAILS"
export const ADD_SUB_CATETORY = "ADD_SUB_CATETORY"
export const UPDATE_SUB_CATEGORY= "UPDATE_SUB_CATEGORY"
export const DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY"

export const ADD_SPECIFICATION = "ADD_SPECIFICATION"
export const SET_SPECIFICATION_DETAILS = "SET_SPECIFICATION_DETAILS"
export const UPDATE_SPEFICIATION= "UPDATE_SPEFICIATION"
export const DELETE_SPECIFICATION = "DELETE_SPECIFICATION"

export const SET_DRUG_DETAILS = "SET_DRUG_DETAILS"
export const ADD_DRUG = "ADD_DRUG"
export const UPDATE_DRUG= "UPDATE_DRUG"
export const DELETE_DRUG = "DELETE_DRUG"

export const SET_FORMULATION_DETAILS = "SET_FORMULATION_DETAILS"
export const ADD_FORMULATION = "ADD_FORMULATION"
export const UPDATE_FORMULATION= "UPDATE_FORMULATION"
export const DELETE_FORMULATION = "DELETE_FORMULATION"
export const SET_ROLE = "SET_ROLE"
export const SET_ATTRIBUTE = "SET_ATTRIBUTE"
export const SET_PARENT = "SET_PARENT"

// main store
export const SET_VIEW_STOCK_BALANCE_LIST = "SET_VIEW_STOCK_BALANCE_LIST"
export const SET_VIEW_STOCK_BALANCE_DETAIL_LIST = "SET_VIEW_STOCK_BALANCE_DETAIL_LIST"
export const SET_TO_STORE_DETAIL_LIST = "SET_TO_STORE_DETAIL_LIST"
export const SET_DRUG_INDENT_DETAIL_LIST = "SET_DRUG_INDENT_DETAIL_LIST"
export const SET_VIEW_STOCK_BALANCE_EXPIRY_LIST = "SET_VIEW_STOCK_BALANCE_EXPIRY_LIST"
export const DELETE_VIEW_STOCK_BALANCE_EXPIRY = "DELETE_VIEW_STOCK_BALANCE_EXPIRY"
export const SET_RECIEPT_LIST = "SET_RECIEPT_LIST"
export const SET_RECIEPT_LIST_DETAIL = "SET_RECIEPT_LIST_DETAIL"
export const ADD_RECIEPT = "ADD_RECIEPT"
export const FINISH_RECIEPT_THIS_SLIP = "FINISH_RECIEPT_THIS_SLIP"
export const CLEAR_RECIEPT_SLIP = "CLEAR_RECIEPT_SLIP"
export const DELETE_RECIEPT_SLIP = "DELETE_RECIEPT_SLIP"
export const SET_INDENT_LIST = "SET_INDENT_LIST"
export const SET_DRUG_INDENT_LIST = "SET_DRUG_INDENT_LIST"













